export {
  calculateContractBrain,
  confirmFact,
  correctFact,
  createCancellationDraft,
  createOfferComparisonIntent,
  createOrUpdateContractRecord,
  deleteContractRecord,
  factLabels,
  getContractRecord,
  getExtractedFacts,
  getMissingRequiredFacts,
  knowledgeStorageKey,
  listContractRecords,
  listContractsNeedingReview,
  listMissingFacts,
  managedPersonProfiles,
  markActionDraftPrepared,
  markFactMissing,
  saveExtractedFacts,
  updateActionDraftBody,
  updateContractRecord,
} from "./knowledge-service";
